export const VALIDATION_CRITERIA = {
  emailMaxLength: 30,
  passwordMinLength: 8,
  passwordMaxLength: 14,
  nameMinLength: 1,
  nameMaxLength: 50,
  subTitleMinLength: 2,
  subTitleMaxLength: 150,
  titleMinLength: 2,
  titleMaxLength: 60,
  phoneMinLength: 8,
  phoneMaxLength: 14,
  codeMinLength: 6,
  codeMaxLength: 6,
  faqQuestion: 150,
  notificationTitle: 150,
  notificationDesc: 300,
  faqAnswer: 1000,
  deactivateReasonMinLength: 1,
  deactivateReasonMaxLength: 250,
};
